### ISSUE TITLE
Docs: not clear how to build and run the project

### ISSUE THREAD

**Issue by neginsadeghi** [NeuraLegion/brokencrystals#132]
I just couldn't run it with the following approach, can you please gimme a more detailed approach for running this repo ? 

Building and Running the Application
# build server
npm ci --prefix public && npm run build --prefix public

# build client 
npm ci && npm run build

#build and start dockers with Postgres DB, nginx and server
docker-compose up -d

**Comment by neginsadeghi** [comment]
TY, It seems working now,

is there any frontend for this vulnerable app ( based on the api ) ? 

and is there anyway to change the domain name to my own for testing purposes ( any env variable or something ) ?

**Comment by derevnjuk** [comment]
Closed by #17
