### ISSUE TITLE
Prepare a GitLab like CI example for CircleCI

### ISSUE THREAD

**Issue by rielas** [NeuraLegion/brokencrystals#22]
It should be a public GitHub repo with CircleCI configuration.

It should run a crawler against https://brokencrystals.neuralegion.com

**Comment by rielas** [comment]
@danizz91 Could you leave here a short report on where we can find this project? Also, move it to "To Verify"

**Comment by danizz91** [comment]
I've created one project with 2 branches:
1.) circleci-project-setup branch creating new scan on "Broken Crystal" with API_TOKEN
2.) repeater branch using docker compose ( repeater image and juiceshop image ) and create new scan through the repeater and running it on local juice shop from ( docker image ).
you can find it on : https://app.circleci.com/pipelines/github/danizz91/circleci-BC

**Comment by rielas** [comment]
Nice. The only request: move such tasks into "To verify" column
<img width="509" alt="image" src="https://user-images.githubusercontent.com/566171/110435629-4ab12200-80c4-11eb-8425-d3297816839e.png">
