### ISSUE TITLE
brokencrystals-nodejs container keeps restarting

### ISSUE THREAD

**Issue by knoxSWS** [NeuraLegion/brokencrystals#224]
Hi there, I forked a copy of the repo and tried to run this locally on my Windows 10 device using Docker Desktop (WSL2). I had to modify the Dockerfile at the root dir, first line to "from node:16" as I was getting an error at the "RUN npm ci -q". 

=> CACHED [brokencrystals-nodejs  3/13] COPY package*.json ./                                                                                                                                                          0.0s
 => ERROR [brokencrystals-nodejs  4/13] RUN npm ci -q                                                                                                                                                                   0.9s
 => CACHED [brokencrystals-proxy builder  2/11] WORKDIR /home/node/bc                                                                                                                                                   0.0s
 => CACHED [brokencrystals-proxy builder  3/11] COPY package*.json ./                                                                                                                                                   0.0s
 => CANCELED [brokencrystals-proxy builder  4/11] RUN npm ci -q                                                                                                                                                         1.0s
------
 > [brokencrystals-nodejs  4/13] RUN npm ci -q:
#0 0.914 npm ERR! Cannot read property '@mikro-orm/core' of undefined
#0 0.920
#0 0.920 npm ERR! A complete log of this run can be found in:
#0 0.920 npm ERR!     /root/.npm/_logs/2022-12-12T19_59_32_263Z-debug.log
------
failed to solve: executor failed running [/bin/sh -c npm ci -q]: exit code: 1

By modifying to node:16 this allowed it to complete, however the container is unable to start due to the error below: 

> broken-crystals@0.0.1 start:prod
> node dist/main.js

/var/www/node_modules/bindings/bindings.js:91
        throw e
        ^

Error: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /var/www/node_modules/libxmljs/build/Release/xmljs.node)
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1239:18)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
    at Function.Module._load (node:internal/modules/cjs/loader:868:12)
    at Module.require (node:internal/modules/cjs/loader:1057:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at bindings (/var/www/node_modules/bindings/bindings.js:84:48)
    at Object.<anonymous> (/var/www/node_modules/libxmljs/lib/bindings.js:1:37)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Module.load (node:internal/modules/cjs/loader:1033:32) {
  code: 'ERR_DLOPEN_FAILED'
}

Is there any more documentation on how to get it running locally? Any help is much appreciated

**Comment by Kif-Fando** [comment]
@knoxSWS try run _docker-compose -f docker-compose.local.yml up_

**Comment by knoxSWS** [comment]
> @knoxSWS try run _docker-compose -f docker-compose.local.yml up_

Hi @Kif-Fando , thanks for coming back to me. 
So if I delete all local containers, images etc locally and start fresh running the suggested command with "FROM node:14" I get the below. If I modify that to "FROM node:16" I get the same issue as before (see further down)

docker-compose -f docker-compose.local.yml up
time="2022-12-13T10:27:16Z" level=warning msg="The \"POSTGRES_USER\" variable is not set. Defaulting to a blank string."
time="2022-12-13T10:27:16Z" level=warning msg="The \"POSTGRES_PASSWORD\" variable is not set. Defaulting to a blank string."
[+] Running 14/14
 - db Pulled                                                                                                                                                      69.1s
   - 025c56f98b67 Already exists                                                                                                                                   0.0s
   - 26dc25c16f4e Pull complete                                                                                                                                    7.8s
   - a032d8a894de Pull complete                                                                                                                                    7.9s
   - 40dba7d35750 Pull complete                                                                                                                                    8.3s
   - 8ebb44a56070 Pull complete                                                                                                                                   10.4s
   - 813fd6cf203b Pull complete                                                                                                                                   10.7s
   - 7024f61bf8f5 Pull complete                                                                                                                                   10.9s
   - 23f986b322e8 Pull complete                                                                                                                                   11.1s
   - 1fb05ff7a8d6 Pull complete                                                                                                                                   65.4s
   - 74afc7d9bc5c Pull complete                                                                                                                                   65.6s
   - 7c2c7eebef2f Pull complete                                                                                                                                   65.8s
   - bdd9df7f1d37 Pull complete                                                                                                                                   65.9s
   - 33d269a3a052 Pull complete                                                                                                                                   66.1s
[+] Building 23.2s (28/37)
 => [brokencrystals-nodejs internal] load build definition from Dockerfile                                                                                         0.1s
 => => transferring dockerfile: 470B                                                                                                                               0.0s
 => [brokencrystals-proxy internal] load build definition from Dockerfile.local                                                                                    0.1s
 => => transferring dockerfile: 38B                                                                                                                                0.0s
 => [brokencrystals-nodejs internal] load .dockerignore                                                                                                            0.1s
 => => transferring context: 34B                                                                                                                                   0.0s
 => [brokencrystals-proxy internal] load .dockerignore                                                                                                             0.0s
 => => transferring context: 2B                                                                                                                                    0.0s
 => [brokencrystals-nodejs internal] load metadata for docker.io/library/node:14                                                                                   1.9s
 => [brokencrystals-proxy internal] load metadata for docker.io/library/nginx:latest                                                                               1.7s
 => [brokencrystals-nodejs internal] load build context                                                                                                           18.9s
 => => transferring context: 6.51kB                                                                                                                               18.9s
 => [brokencrystals-nodejs  1/15] FROM docker.io/library/node:14@sha256:f11e8dbf2ff6668927aafd90a804bf6597d8fe53dc16742a234045f7bf647a8c                           0.0s
 => [brokencrystals-proxy http 1/3] FROM docker.io/library/nginx@sha256:ab589a3c466e347b1c0573be23356676df90cd7ce2dbf6ec332a5f0a8b5e59db                           0.0s
 => [brokencrystals-proxy internal] load build context                                                                                                            18.9s
 => => transferring context: 43.71kB                                                                                                                              18.9s
 => CACHED [brokencrystals-nodejs  2/15] WORKDIR /var/www/                                                                                                         0.0s
 => CACHED [brokencrystals-nodejs  3/15] COPY package-lock.json ./                                                                                                 0.0s
 => CACHED [brokencrystals-nodejs  4/15] COPY package*.json ./                                                                                                     0.0s
 => CACHED [brokencrystals-nodejs  5/15] RUN npm i libxmljs                                                                                                        0.0s
 => ERROR [brokencrystals-nodejs  6/15] RUN npm ci -q                                                                                                              1.8s
 => CACHED [brokencrystals-proxy builder  2/11] WORKDIR /home/node/bc                                                                                              0.0s
 => CACHED [brokencrystals-proxy builder  3/11] COPY package*.json ./                                                                                              0.0s
 => CACHED [brokencrystals-proxy builder  4/11] RUN npm ci -q                                                                                                      0.0s
 => CACHED [brokencrystals-proxy builder  5/11] COPY .env ./                                                                                                       0.0s
 => CACHED [brokencrystals-proxy builder  6/11] COPY tsconfig.json ./                                                                                              0.0s
 => CACHED [brokencrystals-proxy builder  7/11] COPY src ./src                                                                                                     0.0s
 => CACHED [brokencrystals-proxy builder  8/11] COPY typings ./typings                                                                                             0.0s
 => CACHED [brokencrystals-proxy builder  9/11] COPY public ./public                                                                                               0.0s
 => CACHED [brokencrystals-proxy builder 10/11] COPY vcs ./vcs                                                                                                     0.0s
 => CACHED [brokencrystals-proxy builder 11/11] RUN npm run build                                                                                                  0.0s
 => CACHED [brokencrystals-proxy http 2/3] COPY --from=builder  /home/node/bc/build /var/www/html                                                                  0.0s
 => CACHED [brokencrystals-proxy http 3/3] COPY ./nginx-config/default.conf /etc/nginx/conf.d/default.conf                                                         0.0s
 => [brokencrystals-proxy] exporting to image                                                                                                                      0.0s
 => => exporting layers                                                                                                                                            0.0s
 => => writing image sha256:5b2ab69d477757163f6b0c50417a799da5d2b2582072c4a897c1b53451a32fe9                                                                       0.0s
 => => naming to docker.io/library/brokencrystals-proxy                                                                                                            0.0s
------
 > [brokencrystals-nodejs  6/15] RUN npm ci -q:
#0 1.514 npm WARN prepare removing existing node_modules/ before installation
#0 1.619 npm ERR! cipm can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
#0 1.619 npm ERR!
#0 1.620 npm ERR!
#0 1.620 npm ERR! Missing: @mikro-orm/core@^4.3.3
#0 1.620 npm ERR! Missing: @mikro-orm/nestjs@^4.2.0
...... CONTINUES WITH MORE PACKAGES
#0 1.633 npm ERR!
#0 1.741
#0 1.741 npm ERR! A complete log of this run can be found in:
#0 1.741 npm ERR!     /root/.npm/_logs/2022-12-13T10_28_50_403Z-debug.log
------
failed to solve: executor failed running [/bin/sh -c npm ci -q]: exit code: 1


END OF FROM NODE14.

NOW FROM NODE 16

docker-compose -f docker-compose.local.yml up
time="2022-12-13T10:45:17Z" level=warning msg="The \"POSTGRES_USER\" variable is not set. Defaulting to a blank string."
time="2022-12-13T10:45:17Z" level=warning msg="The \"POSTGRES_PASSWORD\" variable is not set. Defaulting to a blank string."
[+] Running 14/14
 - db Pulled                                                                                                                                                      69.8s
   - 025c56f98b67 Already exists                                                                                                                                   0.0s
   - 26dc25c16f4e Pull complete                                                                                                                                    7.4s
   - a032d8a894de Pull complete                                                                                                                                    7.5s
   - 40dba7d35750 Pull complete                                                                                                                                    7.6s
   - 8ebb44a56070 Pull complete                                                                                                                                   12.0s
   - 813fd6cf203b Pull complete                                                                                                                                   12.2s
   - 7024f61bf8f5 Pull complete                                                                                                                                   12.4s
   - 23f986b322e8 Pull complete                                                                                                                                   12.6s
   - 1fb05ff7a8d6 Pull complete                                                                                                                                   66.3s
   - 74afc7d9bc5c Pull complete                                                                                                                                   66.5s
   - 7c2c7eebef2f Pull complete                                                                                                                                   66.6s
   - bdd9df7f1d37 Pull complete                                                                                                                                   66.8s
   - 33d269a3a052 Pull complete                                                                                                                                   67.0s
[+] Building 19.0s (39/39) FINISHED
 => [brokencrystals-proxy internal] load build definition from Dockerfile.local                                                                                    0.1s
 => => transferring dockerfile: 38B                                                                                                                                0.0s
 => [brokencrystals-nodejs internal] load build definition from Dockerfile                                                                                         0.0s
 => => transferring dockerfile: 32B                                                                                                                                0.0s
 => [brokencrystals-proxy internal] load .dockerignore                                                                                                             0.1s
 => => transferring context: 2B                                                                                                                                    0.0s
 => [brokencrystals-nodejs internal] load .dockerignore                                                                                                            0.1s
 => => transferring context: 34B                                                                                                                                   0.0s
 => [brokencrystals-proxy internal] load metadata for docker.io/library/nginx:latest                                                                               2.0s
 => [brokencrystals-proxy internal] load metadata for docker.io/library/node:14                                                                                    2.2s
 => [brokencrystals-nodejs internal] load metadata for docker.io/library/node:16                                                                                   2.2s
 => [brokencrystals-proxy internal] load build context                                                                                                            16.0s
 => => transferring context: 43.71kB                                                                                                                              16.0s
 => [brokencrystals-proxy builder  1/11] FROM docker.io/library/node:14@sha256:f11e8dbf2ff6668927aafd90a804bf6597d8fe53dc16742a234045f7bf647a8c                    0.0s
 => [brokencrystals-proxy http 1/3] FROM docker.io/library/nginx@sha256:ab589a3c466e347b1c0573be23356676df90cd7ce2dbf6ec332a5f0a8b5e59db                           0.0s
 => [brokencrystals-nodejs  1/15] FROM docker.io/library/node:16@sha256:7f404d09ceb780c51f4fac7592c46b8f21211474aacce25389eb0df06aaa7472                           0.0s
 => [brokencrystals-nodejs internal] load build context                                                                                                           15.9s
 => => transferring context: 7.68kB                                                                                                                               15.9s
 => CACHED [brokencrystals-proxy builder  2/11] WORKDIR /home/node/bc                                                                                              0.0s
 => CACHED [brokencrystals-proxy builder  3/11] COPY package*.json ./                                                                                              0.0s
 => CACHED [brokencrystals-proxy builder  4/11] RUN npm ci -q                                                                                                      0.0s
 => CACHED [brokencrystals-proxy builder  5/11] COPY .env ./                                                                                                       0.0s
 => CACHED [brokencrystals-proxy builder  6/11] COPY tsconfig.json ./                                                                                              0.0s
 => CACHED [brokencrystals-proxy builder  7/11] COPY src ./src                                                                                                     0.0s
 => CACHED [brokencrystals-proxy builder  8/11] COPY typings ./typings                                                                                             0.0s
 => CACHED [brokencrystals-proxy builder  9/11] COPY public ./public                                                                                               0.0s
 => CACHED [brokencrystals-proxy builder 10/11] COPY vcs ./vcs                                                                                                     0.0s
 => CACHED [brokencrystals-proxy builder 11/11] RUN npm run build                                                                                                  0.0s
 => CACHED [brokencrystals-proxy http 2/3] COPY --from=builder  /home/node/bc/build /var/www/html                                                                  0.0s
 => CACHED [brokencrystals-proxy http 3/3] COPY ./nginx-config/default.conf /etc/nginx/conf.d/default.conf                                                         0.0s
 => [brokencrystals-nodejs] exporting to image                                                                                                                     0.1s
 => => exporting layers                                                                                                                                            0.0s
 => => writing image sha256:5b2ab69d477757163f6b0c50417a799da5d2b2582072c4a897c1b53451a32fe9                                                                       0.0s
 => => naming to docker.io/library/brokencrystals-proxy                                                                                                            0.0s
 => => writing image sha256:288f95b46f9a9c7e222a3372a1d3fb61e0ae40661e653244f19664e9ebcfcbc5                                                                       0.0s
 => => naming to docker.io/library/brokencrystals-nodejs                                                                                                           0.0s
 => CACHED [brokencrystals-nodejs  2/15] WORKDIR /var/www/                                                                                                         0.0s
 => CACHED [brokencrystals-nodejs  3/15] COPY package-lock.json ./                                                                                                 0.0s
 => CACHED [brokencrystals-nodejs  4/15] COPY package*.json ./                                                                                                     0.0s
 => CACHED [brokencrystals-nodejs  5/15] RUN npm i libxmljs                                                                                                        0.0s
 => CACHED [brokencrystals-nodejs  6/15] RUN npm ci -q                                                                                                             0.0s
 => CACHED [brokencrystals-nodejs  7/15] COPY config ./config                                                                                                      0.0s
 => CACHED [brokencrystals-nodejs  8/15] COPY tsconfig.build.json ./                                                                                               0.0s
 => CACHED [brokencrystals-nodejs  9/15] COPY tsconfig.json ./                                                                                                     0.0s
 => CACHED [brokencrystals-nodejs 10/15] COPY nest-cli.json ./                                                                                                     0.0s
 => CACHED [brokencrystals-nodejs 11/15] COPY .env ./                                                                                                              0.0s
 => CACHED [brokencrystals-nodejs 12/15] COPY src ./src                                                                                                            0.0s
 => CACHED [brokencrystals-nodejs 13/15] RUN npm run build                                                                                                         0.0s
 => CACHED [brokencrystals-nodejs 14/15] RUN npm prune --production                                                                                                0.0s
 => CACHED [brokencrystals-nodejs 15/15] RUN chown -R node:node /var/www/*                                                                                         0.0s

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
[+] Running 4/4
 - Network brokencrystals_default    Created                                                                                                                       0.9s
 - Container brokencrystals-db-1     Created                                                                                                                       0.2s
 - Container nodejs                  Created                                                                                                                       0.2s
 - Container brokencrystals-proxy-1  Created                                                                                                                       0.2s
Attaching to brokencrystals-db-1, brokencrystals-proxy-1, nodejs
brokencrystals-db-1     | The files belonging to this database system will be owned by user "postgres".
brokencrystals-db-1     | This user must also own the server process.
brokencrystals-db-1     |
brokencrystals-db-1     | The database cluster will be initialized with locale "en_US.utf8".
brokencrystals-db-1     | The default database encoding has accordingly been set to "UTF8".
brokencrystals-db-1     | The default text search configuration will be set to "english".
brokencrystals-db-1     |
brokencrystals-db-1     | Data page checksums are disabled.
brokencrystals-db-1     |
brokencrystals-db-1     | fixing permissions on existing directory /var/lib/postgresql/data ... ok
brokencrystals-db-1     | creating subdirectories ... ok
brokencrystals-db-1     | selecting dynamic shared memory implementation ... posix
brokencrystals-db-1     | selecting default max_connections ... 100
brokencrystals-db-1     | selecting default shared_buffers ... 128MB
brokencrystals-db-1     | selecting default time zone ... Etc/UTC
brokencrystals-db-1     | creating configuration files ... ok
brokencrystals-db-1     | running bootstrap script ... ok
brokencrystals-db-1     | performing post-bootstrap initialization ... ok
brokencrystals-db-1     | syncing data to disk ... initdb: warning: enabling "trust" authentication for local connections
brokencrystals-db-1     | initdb: hint: You can change this by editing pg_hba.conf or using the option -A, or --auth-local and --auth-host, the next time you run initdb.
brokencrystals-db-1     | ok
brokencrystals-db-1     |
brokencrystals-db-1     |
brokencrystals-db-1     | Success. You can now start the database server using:
brokencrystals-db-1     |
brokencrystals-db-1     |     pg_ctl -D /var/lib/postgresql/data -l logfile start
brokencrystals-db-1     |
brokencrystals-db-1     | waiting for server to start....2022-12-13 10:46:54.749 UTC [48] LOG:  starting PostgreSQL 15.1 (Debian 15.1-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
brokencrystals-db-1     | 2022-12-13 10:46:54.752 UTC [48] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
brokencrystals-db-1     | 2022-12-13 10:46:54.763 UTC [51] LOG:  database system was shut down at 2022-12-13 10:46:53 UTC
brokencrystals-db-1     | 2022-12-13 10:46:54.770 UTC [48] LOG:  database system is ready to accept connections
brokencrystals-db-1     |  done
brokencrystals-db-1     | server started
brokencrystals-db-1     | CREATE DATABASE
brokencrystals-db-1     |
brokencrystals-db-1     |
brokencrystals-db-1     | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/pg.sql
brokencrystals-db-1     | SET
brokencrystals-db-1     | SET
brokencrystals-db-1     | CREATE TABLE
brokencrystals-db-1     | CREATE TABLE
brokencrystals-db-1     | CREATE TABLE
brokencrystals-db-1     | SET
brokencrystals-db-1     | INSERT 0 1
brokencrystals-db-1     | INSERT 0 1
brokencrystals-db-1     | INSERT 0 1
brokencrystals-db-1     | INSERT 0 1
brokencrystals-db-1     | INSERT 0 1
brokencrystals-db-1     | INSERT 0 1
brokencrystals-db-1     | INSERT 0 1
brokencrystals-db-1     | INSERT 0 1
brokencrystals-db-1     | INSERT 0 1
brokencrystals-db-1     | INSERT 0 1
nodejs                  |
nodejs                  | > broken-crystals@0.0.1 start:prod
nodejs                  | > node dist/main.js
nodejs                  |
brokencrystals-db-1     | CREATE INDEX
brokencrystals-db-1     |
brokencrystals-db-1     |
brokencrystals-db-1     | waiting for server to shut down...2022-12-13 10:46:55.201 UTC [48] LOG:  received fast shutdown request
brokencrystals-db-1     | .2022-12-13 10:46:55.206 UTC [48] LOG:  aborting any active transactions
brokencrystals-db-1     | 2022-12-13 10:46:55.210 UTC [48] LOG:  background worker "logical replication launcher" (PID 54) exited with exit code 1
brokencrystals-db-1     | 2022-12-13 10:46:55.211 UTC [49] LOG:  shutting down
brokencrystals-db-1     | 2022-12-13 10:46:55.216 UTC [49] LOG:  checkpoint starting: shutdown immediate
brokencrystals-db-1     | 2022-12-13 10:46:55.387 UTC [49] LOG:  checkpoint complete: wrote 935 buffers (5.7%); 0 WAL file(s) added, 0 removed, 0 recycled; write=0.034 s, sync=0.124 s, total=0.177 s; sync files=259, longest=0.008 s, average=0.001 s; distance=4287 kB, estimate=4287 kB
brokencrystals-db-1     | 2022-12-13 10:46:55.393 UTC [48] LOG:  database system is shut down
brokencrystals-db-1     |  done
brokencrystals-db-1     | server stopped
brokencrystals-db-1     |
brokencrystals-db-1     | PostgreSQL init process complete; ready for start up.
brokencrystals-db-1     |
brokencrystals-db-1     | 2022-12-13 10:46:55.430 UTC [1] LOG:  starting PostgreSQL 15.1 (Debian 15.1-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
brokencrystals-db-1     | 2022-12-13 10:46:55.430 UTC [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
brokencrystals-db-1     | 2022-12-13 10:46:55.430 UTC [1] LOG:  listening on IPv6 address "::", port 5432
brokencrystals-db-1     | 2022-12-13 10:46:55.438 UTC [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
brokencrystals-db-1     | 2022-12-13 10:46:55.446 UTC [65] LOG:  database system was shut down at 2022-12-13 10:46:55 UTC
brokencrystals-db-1     | 2022-12-13 10:46:55.455 UTC [1] LOG:  database system is ready to accept connections
brokencrystals-proxy-1  | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
brokencrystals-proxy-1  | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
brokencrystals-proxy-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
nodejs                  | /var/www/node_modules/bindings/bindings.js:91
nodejs                  |         throw e
nodejs                  |         ^
nodejs                  |
nodejs                  | Error: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /var/www/node_modules/libxmljs/build/Release/xmljs.node)
nodejs                  |     at Object.Module._extensions..node (node:internal/modules/cjs/loader:1239:18)
brokencrystals-proxy-1  | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
nodejs                  |     at Module.load (node:internal/modules/cjs/loader:1033:32)
nodejs                  |     at Function.Module._load (node:internal/modules/cjs/loader:868:12)
nodejs                  |     at Module.require (node:internal/modules/cjs/loader:1057:19)
nodejs                  |     at require (node:internal/modules/cjs/helpers:103:18)
nodejs                  |     at bindings (/var/www/node_modules/bindings/bindings.js:84:48)
nodejs                  |     at Object.<anonymous> (/var/www/node_modules/libxmljs/lib/bindings.js:1:37)
nodejs                  |     at Module._compile (node:internal/modules/cjs/loader:1155:14)
nodejs                  |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
brokencrystals-proxy-1  | 10-listen-on-ipv6-by-default.sh: info: /etc/nginx/conf.d/default.conf differs from the packaged version
nodejs                  |     at Module.load (node:internal/modules/cjs/loader:1033:32) {
brokencrystals-proxy-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
nodejs                  |   code: 'ERR_DLOPEN_FAILED'
nodejs                  | }
brokencrystals-proxy-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
brokencrystals-proxy-1  | /docker-entrypoint.sh: Configuration complete; ready for start up
brokencrystals-proxy-1  | 2022/12/13 10:46:56 [notice] 1#1: using the "epoll" event method
brokencrystals-proxy-1  | 2022/12/13 10:46:56 [notice] 1#1: nginx/1.23.2
brokencrystals-proxy-1  | 2022/12/13 10:46:56 [notice] 1#1: built by gcc 10.2.1 20210110 (Debian 10.2.1-6)
brokencrystals-proxy-1  | 2022/12/13 10:46:56 [notice] 1#1: OS: Linux 5.10.16.3-microsoft-standard-WSL2
brokencrystals-proxy-1  | 2022/12/13 10:46:56 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
brokencrystals-proxy-1  | 2022/12/13 10:46:56 [notice] 1#1: start worker processes
brokencrystals-proxy-1  | 2022/12/13 10:46:56 [notice] 1#1: start worker process 28
brokencrystals-proxy-1  | 2022/12/13 10:46:56 [notice] 1#1: start worker process 29
brokencrystals-proxy-1  | 2022/12/13 10:46:56 [notice] 1#1: start worker process 30
brokencrystals-proxy-1  | 2022/12/13 10:46:56 [notice] 1#1: start worker process 31
brokencrystals-proxy-1  | 2022/12/13 10:46:56 [notice] 1#1: start worker process 32
brokencrystals-proxy-1  | 2022/12/13 10:46:56 [notice] 1#1: start worker process 33
brokencrystals-proxy-1  | 2022/12/13 10:46:56 [notice] 1#1: start worker process 34
brokencrystals-proxy-1  | 2022/12/13 10:46:56 [notice] 1#1: start worker process 35
brokencrystals-proxy-1  | 2022/12/13 10:46:56 [notice] 1#1: start worker process 36
brokencrystals-proxy-1  | 2022/12/13 10:46:56 [notice] 1#1: start worker process 37
brokencrystals-proxy-1  | 2022/12/13 10:46:56 [notice] 1#1: start worker process 38
brokencrystals-proxy-1  | 2022/12/13 10:46:56 [notice] 1#1: start worker process 39
nodejs exited with code 1
nodejs                  |
nodejs                  | > broken-crystals@0.0.1 start:prod
nodejs                  | > node dist/main.js
nodejs                  |
nodejs                  | /var/www/node_modules/bindings/bindings.js:91
nodejs                  |         throw e
nodejs                  |         ^
nodejs                  |
nodejs                  | Error: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /var/www/node_modules/libxmljs/build/Release/xmljs.node)
nodejs                  |     at Object.Module._extensions..node (node:internal/modules/cjs/loader:1239:18)
nodejs                  |     at Module.load (node:internal/modules/cjs/loader:1033:32)
nodejs                  |     at Function.Module._load (node:internal/modules/cjs/loader:868:12)
nodejs                  |     at Module.require (node:internal/modules/cjs/loader:1057:19)
nodejs                  |     at require (node:internal/modules/cjs/helpers:103:18)
nodejs                  |     at bindings (/var/www/node_modules/bindings/bindings.js:84:48)
nodejs                  |     at Object.<anonymous> (/var/www/node_modules/libxmljs/lib/bindings.js:1:37)
nodejs                  |     at Module._compile (node:internal/modules/cjs/loader:1155:14)
nodejs                  |     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
nodejs                  |     at Module.load (node:internal/modules/cjs/loader:1033:32) {
nodejs                  |   code: 'ERR_DLOPEN_FAILED'
nodejs                  | }
nodejs exited with code 1
brokencrystals-db-1     | 2022-12-13 10:47:02.680 UTC [77] FATAL:  role "root" does not exist
nodejs                  |
nodejs                  | > broken-crystals@0.0.1 start:prod
nodejs                  | > node dist/main.js
nodejs                  |
nodejs                  | /var/www/node_modules/bindings/bindings.js:91
nodejs                  |         throw e

**Comment by Kif-Fando** [comment]
@knoxSWS show me pls your _package.json_

**Comment by knoxSWS** [comment]
@Kif-Fando - ok, I have found that if I clone repo to Win 10 and skip the build steps and just run the docker, it seems to work.
# build server
npm ci && npm run build

# build client
npm ci --prefix public && npm run build --prefix public

What I have done instead is used ubuntu 18.04 in WSL and followed build steps then docker and that works too. (slicker than windows). Thanks for the help, I think you can close the issue. probably just user error here.
