### ISSUE TITLE
Create a developer version of docker-compose

### ISSUE THREAD

**Issue by rielas** [NeuraLegion/brokencrystals#24]

**Comment by Kafva** [comment]
Not sure if this is what you mean, but I recently tried to run the project using the `docker-compose` instructions in the README and only got empty responses from the `proxy` service. However, I was seemingly able to create a fix: 

1. I used the default `docker-compose.yml` file but with the `proxy` from `docker-compose.local.yml`
2. Modified `local.conf` to include routes from `default.conf` 
3. Installed `eslint-plugin-prettier` (see issue #60) 
4. Changed all occurrences of `%PUBLIC%` to `public` in `index.html` (from the comments I assume this should not be needed)

I am not sure if I missed something and the instructions in the README are correct or if the instructions are only meant for the core devs? If they are not meant to be applicable for anyone that clones the project I feel like you should clearly state that in the README.

I have a patch with the changes I made [here](https://gist.github.com/Kafva/4fc9f9bb6924070d09980ec7fc569b43) if anyone is interested.

**Comment by rielas** [comment]
@tamirGer @Kif-Fando Could you review if it's useful for us?
