### ISSUE TITLE
The typo in counters

### ISSUE THREAD

**Issue by bararchy** [NeuraLegion/brokencrystals#69]
@wehackpurple found a bug while we were filming! yey! :tada: 

We guess it should say "messages" and not "Massages"? like depends on the services we supply :sweat_smile: 

![image](https://user-images.githubusercontent.com/1631073/129619864-3a9a63c7-b6ec-41da-b8cd-e6b1b7087141.png)

![image](https://user-images.githubusercontent.com/1631073/129620017-e2ea1dec-bb5a-4db4-8f42-81879a76854c.png)

**Comment by tamirGer** [comment]
@derevnjuk @bararchy I'm pretty sure it's Massage stones 😆

**Comment by bararchy** [comment]
If @ArtLinkov approves it's massages who am I to argue XD

**Comment by ArtLinkov** [comment]
Well, if you are playing D&D it may very well be "Message" Stones :laughing:
